name       : libnss
version    : 3.34.1
release    : 21
source     :
    - https://ftp.mozilla.org/pub/security/nss/releases/NSS_3_34_1_RTM/src/nss-3.34.1.tar.gz : a3c15d367caf784f33d96dbafbdffc16a8e42fb8c8aedfce97bf92a9f918dda0
license    :
    - GPL-2.0
    - LGPL-2.1
    - MPL-2.0
component  : system.base
emul32     : yes
libsplit   : no
summary    : Network Security Services
description: |
    The Network Security Services (NSS) package is a set of libraries designed to support cross-platform development of security-enabled client and server applications. Applications built with NSS can support SSL v2 and v3, TLS, PKCS #5, PKCS #7, PKCS #11, PKCS #12, S/MIME, X.509 v3 certificates, and other security standards. This is useful for implementing SSL and S/MIME or other Internet security standards into an application.
builddeps  :
    - pkgconfig32(nspr)
    - pkgconfig32(sqlite3)
    - pkgconfig32(zlib)
patterns   :
    - 32bit-devel:
        - /usr/lib32/nss/lib*.a
        - /usr/lib32/*.a
    - devel:
        - /usr/lib64/nss/lib*.a
        - /usr/lib64/*.a
setup      : |
    %patch -p1 < $pkgfiles/nss-3.34.1-standalone-1.patch
build      : |
    export BUILD_OPT=1
    export NSPR_INCLUDE_DIR="/usr/include/nspr"
    export USE_SYSTEM_ZLIB=1
    export NSS_USE_SYSTEM_SQLITE=1

    if [[ -z "${EMUL32BUILD}" ]]; then
        export USE_64=1
    fi

    pushd nss
        make nss_build_all -j1
    popd
install    : |
    if [[ -z "${EMUL32BUILD}" ]]; then
        mkdir -p $installdir/usr/bin
        for f in certutil modutil pk12util signtool ssltap nss-config; do
            install -m00755 dist/Linux*/bin/${f} $installdir/usr/bin
        done
    fi

    # Headers
    install -d -m00755 $installdir/usr/include/nss
    for f in dist/public/nss/*.h dist/private/nss/*.h; do
        install -m00644 ${f} $installdir/usr/include/nss
    done

    install -d -m00755 $installdir/%libdir%/nss
    for f in *.a *.chk *.so; do
        install dist/Linux*/lib/${f} $installdir/%libdir%/nss
    done

    # Install nss.pc
    install -D -m00644 dist/Linux*/lib/pkgconfig/nss.pc $installdir/%libdir%/pkgconfig/nss.pc

    for f in libcrmf.a libfreebl3.so libnssutil3.so libnss3.so libsmime3.so libnssckbi.so \
             libsoftokn3.so libnssdbm3.so libssl3.so libnsssysinit.so; do
        ln -s %libdir%/nss/${f} $installdir/%libdir%/${f}
    done
